/* Generated By:JJTree: Do not edit this line. ASTEquivalent.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTEquivalent extends SimpleNode {
  public ASTEquivalent(int id) {
    super(id);
  }

  public ASTEquivalent(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6743068a608148943343112314c9b6a3 (do not edit this line) */
