/* Generated By:JJTree: Do not edit this line. ASTForAll.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTForAll extends SimpleNode {
  public ASTForAll(int id) {
    super(id);
  }

  public ASTForAll(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a569fa13a29b5e7bc9997f4540422dac (do not edit this line) */
