/* Generated By:JJTree: Do not edit this line. ASTFormula.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTFormula extends SimpleNode {
  public ASTFormula(int id) {
    super(id);
  }

  public ASTFormula(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=861a2ac773ca50c6e15e37bec15cbfa9 (do not edit this line) */
