/* Generated By:JJTree: Do not edit this line. ASTImplies.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTImplies extends SimpleNode {
  public ASTImplies(int id) {
    super(id);
  }

  public ASTImplies(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a911dfb86feea276c0207e6d84794e2c (do not edit this line) */
