/* Generated By:JJTree: Do not edit this line. ASTPredicate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTPredicate extends SimpleNode {
  public ASTPredicate(int id) {
    super(id);
  }

  public ASTPredicate(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9f4f6c2b88a1ca58790b6341bab87e1 (do not edit this line) */
