/* Generated By:JJTree: Do not edit this line. ASTThereExists.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

public
class ASTThereExists extends SimpleNode {
  public ASTThereExists(int id) {
    super(id);
  }

  public ASTThereExists(Parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38ed6dbdd7f8753b56171d5ce16b5720 (do not edit this line) */
