/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.proof.builder.parser;

public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTIMPLIES = 1;
  public int JJTEQUIVALENT = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTNOT = 5;
  public int JJTFORALL = 6;
  public int JJTTHEREEXISTS = 7;
  public int JJTPREDICATE = 8;


  public String[] jjtNodeName = {
    "void",
    "Implies",
    "Equivalent",
    "And",
    "Or",
    "Not",
    "ForAll",
    "ThereExists",
    "Predicate",
  };
}
/* JavaCC - OriginalChecksum=1175686729c62cee50bdbb1cab366006 (do not edit this line) */
