/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.proof.builder.parser;

public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTEQUALS = 1;
  public int JJTIMPLIES = 2;
  public int JJTEQUIVALENT = 3;
  public int JJTAND = 4;
  public int JJTOR = 5;
  public int JJTNOT = 6;
  public int JJTFORALL = 7;
  public int JJTTHEREEXISTS = 8;
  public int JJTVARIABLE = 9;
  public int JJTPREDICATE = 10;


  public String[] jjtNodeName = {
    "void",
    "Equals",
    "Implies",
    "Equivalent",
    "And",
    "Or",
    "Not",
    "ForAll",
    "ThereExists",
    "Variable",
    "Predicate",
  };
}
/* JavaCC - OriginalChecksum=f2e137298e19fa3898fbe23b24676892 (do not edit this line) */
