/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package logic.proof.builder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPLIES = 1;
  /** RegularExpression Id. */
  int EQUIVALENT = 2;
  /** RegularExpression Id. */
  int AND = 3;
  /** RegularExpression Id. */
  int OR = 4;
  /** RegularExpression Id. */
  int LBRACKET = 5;
  /** RegularExpression Id. */
  int RBRACKET = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int PREDICATE = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<IMPLIES>",
    "<EQUIVALENT>",
    "<AND>",
    "<OR>",
    "<LBRACKET>",
    "<RBRACKET>",
    "<NOT>",
    "<PREDICATE>",
  };

}
