/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package logic.proof.builder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUALS = 1;
  /** RegularExpression Id. */
  int IMPLIES = 2;
  /** RegularExpression Id. */
  int EQUIVALENT = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int OR = 5;
  /** RegularExpression Id. */
  int LBRACKET = 6;
  /** RegularExpression Id. */
  int RBRACKET = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int FORALL = 9;
  /** RegularExpression Id. */
  int THEREEXISTS = 10;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int PREDICATE = 12;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EQUALS>",
    "<IMPLIES>",
    "<EQUIVALENT>",
    "<AND>",
    "<OR>",
    "<LBRACKET>",
    "<RBRACKET>",
    "<NOT>",
    "<FORALL>",
    "<THEREEXISTS>",
    "<VARIABLE>",
    "<PREDICATE>",
  };

}
