/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package logic.proof.builder.parser;

public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTIMPLIES = 1;
  public int JJTEQUIVALENT = 2;
  public int JJTAND = 3;
  public int JJTOR = 4;
  public int JJTPREDICATE = 5;
  public int JJTNOT = 6;


  public String[] jjtNodeName = {
    "void",
    "Implies",
    "Equivalent",
    "And",
    "Or",
    "Predicate",
    "Not",
  };
}
/* JavaCC - OriginalChecksum=3fd9c6ab8dff7be02a85340832aab6e3 (do not edit this line) */
