/* Generated By:JavaCC: Do not edit this line. TokenManager.java Version 5.0 */
/* JavaCCOptions:SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package logic.proof.builder.parser;

/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */

public interface TokenManager {

  /** This gets the next token from the input stream.
   *  A token of kind 0 (<EOF>) should be returned on EOF.
   */
  public Token getNextToken();

}
/* JavaCC - OriginalChecksum=ee77482cc16993fa0976277d87b45b79 (do not edit this line) */
